name: Deploy Workflow

on:
  push:
    branches:
      - development
      - production

jobs:
  # deploy-development:
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/development'
  #   steps:
  #     - name: Stage Tests
  #       run: echo "No Tests to Run, Exiting..."

  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Initialize Container
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ vars.EC2_HOST }} >> ~/.ssh/known_hosts
          printf '%s\n' "${{ secrets.EC2_PEM }}" >> ~/.ssh/id_rsa
          printf "Host ec2\n HostName %s\n User %s\n IdentityFile ~/.ssh/id_rsa\n" "${{ vars.EC2_HOST }}" "${{ vars.EC2_USER }}" >> ~/.ssh/config

      - name: Deploy to EC2
        run: |
          ssh ec2 '
          cd /var/mean/elmwoodarmory/
          && git pull origin production
          && cd client/ && npm install
          && ng build --configuration production
          && cd ../server/ && npm install
          && npx tsc && pm2 startOrRestart ecosystem.config.js'
